### ISSUE TITLE
Node 14: Getting error:  SyntaxError: Unexpected token '||=' On latest release. 

### ISSUE THREAD

**Issue by anoopsivasankaran** [jridgewell/sourcemaps#14]
Unfortunately we are using node 14. all was working fine. Till the latest update.

**Comment by jridgewell** [comment]
Ack, let me figure out why it's not compiling.

**Comment by dpraczuk** [comment]
Unfortunately, we got the same problem.

**Comment by TippuTraya** [comment]
Even we are getting same issue.

**Comment by Dosia96** [comment]
Same....

**Comment by anoopsivasankaran** [comment]
> Try downgrading to version 0.3.5 using the following code in the package.json in your project:
> 
> "overrides":{ "@jridgewell/gen-mapping":"0.3.5", }

We are not using it directly. We are using it through third party. Babel core

**Comment by jridgewell** [comment]
I set the latest tag back to 0.3.5 again. npm's site it taking forever to update, give it a few minutes.

**Comment by RevanthMBontha** [comment]
@anoopsivasankaran, should still work.

"Node Module Version Overrides
In package.json, the overrides field allows you to specify custom versions or dependencies for specific packages. This can be useful when you need to use a specific version of a dependency that differs from the one specified in the dependency tree.

When you define an override in package.json, npm will use that custom version instead of the default version specified in the dependency tree. This override applies not only to the immediate dependency but also to its transitive dependencies (i.e., dependencies of dependencies)."

**Comment by lesongvi** [comment]
> I set the latest tag back to 0.3.5 again. npm's site it taking forever to update, give it a few minutes.

nice save!

**Comment by chuxin-cs** [comment]
@Jridgewell/gen mapping is being used by @ vue/cli plugin babel and cannot be downgraded

**Comment by RoelN** [comment]
@jridgewell This must've been stressful, thanks for the quick fix! 💖

**Comment by swapnilsparsh** [comment]
Run this command if latest version `v0.3.7` is not working👇🏻

```
npm install -D @jridgewell/gen-mapping@0.3.5
```

**Comment by dpraczuk** [comment]
It works! @jridgewell Thanks a lot for fast reaction

**Comment by dheeraj-jft** [comment]
For us, it is being used as internal dependency, github action build is not working at build time.

**Comment by chuxin-cs** [comment]
packaje.json 中 临时添加 @jridgewell/gen-mapping@0.3.5 等作者解决

**Comment by anoopsivasankaran** [comment]
All good now Thank you @jridgewell for quick response.

**Comment by jridgewell** [comment]
I found my bug, but I'm going to wait till tomorrow before publishing a new version. For now, it looks like npm has updated its caches and now 0.3.5 is appearing as the latest version.
